Added code and tests
jhlfrfufyfn/StringProcessing pull request #1
Opened 2020-09-15 18:38 UTC by jhlfrfufyfn

It's my third Java assignment, variant 7:
"Дан текст. Удалить из него все слова, которые являются числами (состоят только из цифр)."
Solution contains class StringProcessor, RegEx was used there a little.  There are also tests in the test folder.

2020-09-15 20:00 UTC, VeronikaYastr requested changes

2020-09-15 20:00 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +        Scanner cin = new Scanner(System.in);
Тут тоже лучше сканер в try() catch, чтобы он закрыт был после выполнения программы

2020-09-15 20:00 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +        String text = StringProcessor.deleteNumbers(new String(textBuilder));
Можно использовать `textBuilder.toString()` вместо создания через конструктор

2020-09-15 20:00 UTC, VeronikaYastr commented on src/com/bsu/StringProcessor.java
> +        for(int wordIndex = 0;wordIndex < words.length;wordIndex++){
Тоже кривое форматирование, склеилось все. Ctrl+Alt+L в помощь)

2020-09-15 20:00 UTC, VeronikaYastr commented on src/com/bsu/StringProcessor.java
> +        for(int i=0;i<flags.length;i++){
Если с регулярными выражениями, то в принципе можно было сразу сделать

`text.replaceAll("\b\d+\b", "")` - ну только правильно оформить выражение, чтобы метод работал

2020-09-15 20:00 UTC, VeronikaYastr commented on test/com/bsu/StringProcessorTest.java
> +
Тоже вот две пустых строки лишних откуда-то, лучше такое убирать, а то код странно выглядит

Тесты, кстати, удобно разделять на разные кейсы. Чтобы если у тебя упал тест, было сразу понятно какой

2020-09-16 16:27 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +        String text = StringProcessor.deleteNumbers(new String(textBuilder));
Готово

2020-09-16 16:28 UTC, jhlfrfufyfn commented on src/com/bsu/StringProcessor.java
> +        for(int wordIndex = 0;wordIndex < words.length;wordIndex++){
Готово

2020-09-16 16:28 UTC, jhlfrfufyfn commented on test/com/bsu/StringProcessorTest.java
> +
Готово

2020-09-16 16:29 UTC, VeronikaYastr commented
Все хорошо)
Тоже можно мержить🙂

2020-09-16 16:30 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +        Scanner cin = new Scanner(System.in);
Готово

2020-09-16 16:36 UTC, merged